openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - harbor_admin_password
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: harbor
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: harbor-system
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 1.15.0
          x-walrus-ui:
            group: Basic
            order: 3
        harbor_admin_password:
          title: Harbor Admin Password
          type: string
          description: Admin password for Harbor
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
        domain_name:
          title: Domain Name
          type: string
          description: domain name for Harbor, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 5
        dash_domain_name:
          title: Dash Domain Name
          type: string
          description: domain name with dash, e.g. 'dev-domainname-com'
          default: dev-domainname-com
          x-walrus-ui:
            group: Basic
            order: 6
        issuer_name:
          title: Issuer Name
          type: string
          description: origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 7
        issuer_kind:
          title: Issuer Kind
          type: string
          description: origin issuer kind
          default: OriginIssuer
          x-walrus-ui:
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic